cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

install: mvn install --show-version -DskipTests=true  --errors --batch-mode
script: mvn test -B -DskipTests=true

notifications:
  email:
    recipients:
      - raisercostin@gmail.com
      - catalin.ghenea@gmail.com
    on_success: always # default: change
    on_failure: always # default: always